Add functionality to constantly deplete fuel
serious-games-project-lab-2022/unity-project pull request #81
Opened 2023-02-06 14:16 UTC by fredelberger

Fuel is constantly consumed each fixed update

### Closes

- Closes #57

2023-02-06 17:04 UTC, mario-nowak requested changes
Cool!

2023-02-06 17:04 UTC, mario-nowak commented on Assets/Scenes/Pilot/PilotManager.cs
> +     private void FixedUpdate()
The indentation in this line looks weird. Can you fix that?

2023-02-06 17:04 UTC, mario-nowak commented on Assets/Scenes/Pilot/PilotManager.cs
> +        DepleteFuel(0.00007f);
We should probably extract this number into a variable and then multiply it by `Time.FixedDeltaTime` here. Could you change that?

2023-02-06 17:05 UTC, mario-nowak commented
Don't forget to re-request a review once you are done :)

2023-02-10 20:27 UTC, Gauteee approved these changes

2023-02-10 20:28 UTC, merged